import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"],
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Emmanuelochaje.dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.className} ${ovo.className} antialiased overflow-x-hidden leading-8 dark:bg-black dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}
